### ISSUE TITLE
Integrate with callbacks

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker-browser#8]
Would it be possible to integrate some of the plotting functionality (looking at you `StackViewer`)  with bluesky callbacks?

**Comment by danielballan** [comment]
Sorry we left this unanswered for so long. Yes! But consuming a live data stream would complicate the browser considerably, so that is not on the near-term road map.

**Comment by CJ-Wright** [comment]
Hmm ok, it may be good to separate the two halves of the broker, the header listing side and the plotting side. That way the plotting side can be reused as callbacks (xpdview took a crack at this kind of thing, ish)
